name: Java CI with Maven / CMake

on:
  push:
    branches: [ 'master', 'feature/**' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Run MDE Workflow
      - name: Process MDE workflow with Maven
        run: mvn clean install --file pom.xml

      # Build and test Java Racoonsimulator
      - name: Build Java Racoonsimulator
        run: mvn -Dmaven.javadoc.skip=true -B install --file simulators/de.unistuttgart.iste.sqa.mpw.racoonsimulator.java/pom.xml
