name: CI with Maven / CMake

on:
  push:
    branches: [ 'master', 'feature/**' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  call-build-workflow:
    uses: ./.github/workflows/workflow-build.yaml
    secrets:
      MAVEN_REPO_USER: ${{ secrets.MAVEN_REPO_USER }}
      MAVEN_REPO_PASS: ${{ secrets.MAVEN_REPO_PASS }}
